### ISSUE TITLE
Testing fails on MinGW

### ISSUE THREAD

**Issue by fredrik-johansson** [flintlib/flint2#1206] opened 2023-01-13 17:25 UTC
Factoring fails randomly on MinGW in the 2.10 branch:

    The following tests FAILED:
    	1302 - fmpz_factor-test-t-factor_smooth (Exit code 0xc0000374
    )
    Error: Process completed with exit code 8.

This seems to be a consequence of #1201 and the subsequent fix d8fc2fde844c6a4d4dba82dadbf6c2581d5c6ab9.

On trunk, MinGW currently fails completely, presumably due to missing ``FLINT_DLL`` declarations.

**Comment by albinahlback** [comment] 2023-03-07 20:33
As of my PR moving everything to `src/`, the job fails earlier. Perhaps that just because of a change of directory for `libflint.so`, but I'm not sure.

I've been trying to fix the complaints from the CI about plugin for lto objects, but I cannot seem to fix it.

**Comment by fredrik-johansson** [comment] 2023-03-16 15:15
Some progress understanding the build issue: apparently there is a bug in CMake which means CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS does not work on MinGW: https://gitlab.kitware.com/cmake/cmake/-/issues/22092

One of the suggested workarounds is to manually pass ``-Wl,--export-all-symbols`` to the linker.

Actually, the reason why we are seeing the issue in the first place is that we use ``__declspec (dllexport)`` for some but not for all functions (missing for the Arb/Calcium/GR modules), making the build system think that only some things should be exported. *Removing this entirely* enables automatic export and makes the problem go away. This means that we could potentially delete ``FLINT_DLL`` entirely, though maybe it's still needed for the ``_declspec (dllimport)``? (Which I don't understand either.)

You can see on this branch https://github.com/fredrik-johansson/flint2/tree/mingw that building almost succeeds with an empty ``FLINT_DLL`` definition.

Later on there is still this build failure:

    C:/Strawberry/c/lib/libmpfr.a(exceptions.o):(.text+0x0): multiple definition of `mpfr_set_emin'
    lib/libflint.dll.a(d015535.o):(.text+0x0): first defined here
    C:/Strawberry/c/lib/libmpfr.a(exceptions.o):(.text.unlikely+0x17): multiple definition of `mpfr_get_emin_min'
    lib/libflint.dll.a(d015449.o):(.text+0x0): first defined here
    C:/Strawberry/c/lib/libmpfr.a(exceptions.o):(.text+0x40): multiple definition of `mpfr_set_emax'
    lib/libflint.dll.a(d015534.o):(.text+0x0): first defined here
    ...

Not sure how to fix that...

**Comment by isuruf** [comment] 2023-03-16 17:24
`FLINT_DLL` is needed for MSVC builds. Maybe FLINT_DLL can be empty for mingw only?

**Comment by albinahlback** [comment] 2023-03-16 18:11
ChatGPT tells me that you can do something like `link /dump /exports mydll.dll > mydll.def` and then manually edit all the symbols to get a proper definition file (I suppose this can be done with `sed`). Perhaps worth a try?

**Comment by albinahlback** [comment] 2023-03-16 23:33
Had problems with getting a MinGW to work with the regular `configure` and `Makefile` (before it used CMake). What solved the problem was to remove all `*_DLL` (or, equally, `#define FLINT_DLL`). Then all tests should pass except for MSVC, but there CMake should work.

**Comment by albinahlback** [comment] 2023-03-18 12:21
I am trying to debug with gdb on MinGW via Github CI as I do not have access to any Windows machine. See look at my actions under the branch `autoconf_mingw` in my repo.

**Comment by albinahlback** [comment] 2023-03-18 14:07
Looks like there is a bug: https://stackoverflow.com/a/74620721/13527214

Perhaps related to this as I only am able to get MinGW to fail with multithreaded make.

**Comment by albinahlback** [comment] 2023-03-18 14:47
I very much believe it's related to the management of files in `qsieve` under MinGW. Trying to work on it.

**Comment by fredrik-johansson** [comment] 2023-03-18 14:50
Yes, as far as I can tell this was working before merging #1201.

**Comment by albinahlback** [comment] 2023-03-18 16:08
So I do think that `mkstemp` is the better solution here. However, there seems to be multiple bugs with the function on MinGW. I will think of a solution of how to fix this.

In the mean time I will implement a check, done during configuration, to check whether `mkstemp` works on the system.

**Comment by thofma** [comment] 2023-03-18 16:21
> In the mean time I will implement a check, done during configuration, to check whether `mkstemp` works on the system.

Will this hinder cross-compilation? If so, that should be avoided.

**Comment by albinahlback** [comment] 2023-03-18 17:35
I believe cross-compilation is not supported (that's what I remember Bill saying). However, I would like to support cross-compilation, so if `HOST` and `BUILD` are not the same, then that cannot be tested as such tests needs to be executions rather than simply linking or compiling.

**Comment by thofma** [comment] 2023-03-18 17:55
We have been cross-compiling for years with the blessing of the flint maintainers. I believe that if flint 3.0 does not support cross-compilation, this would be a big step backwards.

**Comment by albinahlback** [comment] 2023-03-18 19:07
I believe I found the problem... The problem is that on Github's CI servers, we do not have write access to `/tmp`... Compare these two: [working](https://github.com/albinahlback/flint2/actions/runs/4456852075/jobs/7827569073) and [non-working](https://github.com/albinahlback/flint2/actions/runs/4456815110/jobs/7827508762).

**Comment by albinahlback** [comment] 2023-03-18 19:11
Why do we even need files for this? Do we really require so much space for factoring?

**Comment by thofma** [comment] 2023-03-18 19:33
Last time I tried figuring this out I only found https://github.com/flintlib/flint2/issues/708 as a breadcrumb.

**Comment by fredrik-johansson** [comment] 2023-03-18 19:59
No, it can certainly be done in memory. Someone just has to rewrite the code.

**Comment by albinahlback** [comment] 2023-03-18 20:11
I can't even see a single `fwrite` or `fread` there...

**Comment by fredrik-johansson** [comment] 2023-03-18 20:14
There's ``flint_fprintf".

**Comment by albinahlback** [comment] 2023-03-18 20:16
Yeah, but then one has to parse the input, right? We cannot read and write directly into and into memory, we must parse the data both ways

**Comment by fredrik-johansson** [comment] 2023-03-18 20:19
I suppose you'd rewrite the code to store arrays of integers instead of strings that need to be parsed.

**Comment by albinahlback** [comment] 2023-03-18 22:33
Closed as of #1279.

**Closed by albinahlback** 2023-03-18 22:33 UTC

**Comment by oscarbenjamin** [comment] 2023-08-05 17:17
See the discussion in gh-1334

The fix in gh-1279 did not really fix the problem but just avoids it in CI. The problem still shows up outside of CI e.g.: https://github.com/fredrik-johansson/python-flint/pull/43#issuecomment-1665468728

The OP here suggests that the previous MinGW CI failure was random. A deterministic reproducer of what I think is the same problem from `python_flint` is:
```
fmpz(10**35 + 1).factor()
```

The PR gh-1279 introduces a `TMPDIR` build configuration option whose only purpose seems to be for the MinGW CI job. It should not be used for the MinGW CI job because it is hiding a bug that would still be seen outside of CI. I think that the `TMPDIR` option (which was added since 2.9.0 and is only in 3.0.0-alpha1) should be removed so probably gh-1279 should basically be reverted in full.

This code seems to have changed quite a few times since gh-1201 with various conditional preprocessor macros for different environments and different versions of the code. That makes it difficult to track exactly when it was or was not working on different platforms.

Apart from avoiding the use of temporary files altogether a better option might be to use `tmpfile` instead of `tmpnam` or `mkstemp` as discussed at https://github.com/flintlib/flint2/pull/1334#issuecomment-1666536071. It is possible that `tmpfile` could be used on all platforms without needing any `#ifdef` for Windows.

At least for the MinGW case something else needs to be used because the current code always (except in CI) tries to write to `/tmp` which does not exist on Windows.
